### ISSUE TITLE
[Level2] 택배 배달과 수거하기

### ISSUE THREAD

**Issue by GeonHui2** [Uttug-Seuja/uttug-seuja-algorithm#356]
## 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/150369

## 풀이 사항
풀이 일자: 2023.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

## 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by junjange** [comment]
## 문제 링크

## 풀이 사항
풀이 일자: 2023.08.13
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 자료구조

## 풀이 방법
문제를 봤을 때, 거리가 제일 먼 집부터 배달과 수거를 하면서 진행하면 되는 것으로 보인다.
배달을 처음할 때 몇개의 택배를 배달해야할지 의문을 가졌다. 모든 경우를 확인하기 위해 1부터 n개의 택배를 배달하는 방식으로 해야하는걸까?라고 생각했지만 이것은 매 순간 cap 개수만큼 반복해야하므로 시간초과가 날 것으로 보였다. 
그렇게 다시 생각해보았는데, 택배를 몇개를 하든 최대 cap 개수만큼 해야하고 수거 또한 택배와 상관없이 최대 cap 개수만큼 해야하는 것을 알았다. 따라서 택배와 수거를 별도로 생각하여 수행하면 될 것으로 판단했다.

풀이는 다음과 같다.
- 택배나 수거를 해야하는 제일 먼 거리를 확인한다. (그곳이 택배나 수거를 시작하는 지점)
- 이때, 제일 먼 거리를 갔다가 다시 물류 창고로 돌아오게 되는 것이 한번의 사이클이 된다.
- 제일 먼 거리부터 택배를 진행한다.
- 제일 먼 거리부터 수거를 진행한다.
- 택배와 수거를 다 할 때까지 반복한다.

**Comment by GeonHui2** [comment]
## 문제 링크
#365 

## 풀이 사항
풀이 일자: 2023.08.16
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: 그리디, 구현

## 풀이 방법
처음 문제를 봤을 때, 배달과 수거 중 가장 거리가 먼 곳을 기준으로 계산하면 되는 것으로 보였다.
각각 배달과 수거를 안 해도 되는 집은 소거하면서 새로운 리스트를 정의하고 최대 cap 개수만큼 계산하면서 구현해 봤다.
하지만 첫 시도에서 테스트는 통과했지만 제출했을 때 오답이 나오고 10점을 받았다.
그래서 다른 방법을 생각해 보면서 구현했고 풀이는 다음과 같다.
- 0을 소거하면서 택배와 수거 리스트를 거리가 먼 곳이 먼저 나오게 정렬해서 정의한다.
- 택배와 수거 각각 반복문을 통해서 한 번 갔을 때 시작이 되는 가장 먼 곳을 cnt 리스트에 추가한다.
- 택배 cnt 리스트와 수거 cnt에서 길이가 긴 리스트만큼 짧은 리스트에 0을 추가한다.
- cnt 리스트의 길이만큼 반복문을 통해서  택배와 수거 중 해당 순서에서 더 큰 값을 result에 추가하고 마지막에 result를 2배하고 return 한다.

**Comment by chanu2** [comment]
## 문제 링크
#366 

## 풀이 사항
풀이 일자: 2023.08.16
풀이 시간: 2시간30분
채점 결과: 오답
예상 문제 유형: 구현

## 풀이 방법
-문제를 봤을 때 문제는 이해했지만 어떻게 해야할지 생각해 보았다.
-가장 먼 곳 부터 들려서 로직을 수행하려 했다.
-이차원 배열 리스트를 만들어서 배달해야하는 리스트, 수거해야하는 리스트 두개를  reverse 형태로 만들어서  최대 cap에 맞추어 배달 리스트와 수거 리스트를 제거해 가려 했다.


## 느낀점
문제를 읽고 어떻게 풀어야 할 지 시간이 너무 오래 걸린 것 같다.
구현하는데 어려움을 느꼈다.  리스트를 제거해 나가는게  좋은 방법이 아니라는 것을 느꼈다.  
문제를 많이 풀어 보는게 정답이겠지요?
