### ISSUE TITLE
[Level4] 도둑질

### ISSUE THREAD

**Issue by Leehunil** [Uttug-Seuja/uttug-seuja-algorithm#387]
## 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/42897

## 풀이 사항
풀이 일자: 2023.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

## 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by Leehunil** [comment]
## 문제 링크
#396 

## 풀이 사항
풀이 일자: 2023.08.29
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: DP

## 풀이 방법
- 처음 접근은 DP로 접근하지 못했다. 최대한 많은 집을 터는게 가장 돈이 많을 거라고 생각했다. 반례가 있다.
- 힌트와 친구의 도움으로 DP 유형 문제라는 것을 알게됨
- 먼저 2개의 유형의 DP로 나뉜다. 첫번째 집부터 터는것과 털지 않고 두번쨰 집부터 터는 것 2가지로 나뉜다.
- 먼저 첫번째와 두번째 모두 전전값+현재 돈 과 전값을 비교하여 더 큰값을 저장한다.
- 첫번째는 첫번째집은 무조건 털고 두번째집은 무조건 못터니 dp[0]과 dp[1]은 money[0]으로 둔다.
- 두번째는 첫번째집은 무조건 못털고 두번째집은 무조건 터니 dp[0]=0 과 dp[1]은 money[1]로 둔다.
- 그리고 for문을 돌린다.

**Comment by junjange** [comment]
## 문제 링크
#364 

## 풀이 사항
풀이 일자: 2023.08.16
풀이 시간: 1~2시간
채점 결과: 정답
예상 문제 유형: DP

## 풀이 방법
- 문제를 보면 각 집을 털 수 있는 조건이 있고 그 조건에 맞는 값중에서 최댓값을 구하면 된다고 판단했다.
- 조건에 맞게 집을 하나 하나 터는 것을 보았을 때 DP 문제 인것으로 보이며 점화식을 만들면 쉽게 풀 수 있을 것이라고 생각했다.
- 도둑질을 하는 것도 리스트에 맨 처음부터 진행하는 것과 맨 뒤에서부터 진행하는 것에 따라 값이 달라지는 것을 확인할 수 있었다.
- 난 위 2개의 경우를 모두 확인하기 위해 기존에 있는 리스트와 "reversed" 함수를 사용한 리스트를 통해 확인했다.   
- 또한, 점화식을 생각할때 2가지 경우가 생긴다. 
    - 맨 처음 집을 털면, 마지막 집은 털 수 없다.
    - 두번째 집을 털면, 마지막 집을 털 수 있다.
- 따라서 맨 처음 집을 털었는지에 따라서 DP가 수행되게 구현했다.

**Comment by chanu2** [comment]
## 문제 링크
#398 

## 풀이 사항
풀이 일자: 2023.09.01
풀이 시간: 3시간 30분
채점 결과: 정답
예상 문제 유형: DP

## 풀이 과정
- 처음 접근 모든 경우의 수를 확인해야 한다고 생각해서 bfs인가 dfs인가 했다. 
- 힌트를 통해서 dp문제인 것을 알았고 dp에 대한 10분짜리 영상을 봤다.
- 문제 풀이를 다시 생각해보았다. 첫번째집을 털었을 때 , 2번째 집을 털었을 때 리스트를 각각 만들어 집을 들리면서 최대값을 계속해서 최신화 해주면 되겠다고 생각했다.
- 그렇지만 어떤식으로 최대값을 저장해야 하는지 생각이 나지 않아서 과정을 보고 구현을 해봐야겠다고 생각했다.
- 조건에 맞게 집을 하나 하나 터는 것을 보았을 때 DP 문제 인것으로 보이며 점화식을 만들면 쉽게 풀 수 있을 것이라고 생각했다.
- 집이 3개이면 경우의 수가 정해져 있었기 때문에 미리 리스트에 넣어주었다.
- 현재 집 기준 n-2, n-3 중 최대 값을 구해준다. 
- 첫번째 집을 털었을 때 최대값과 두번째 집을 털었을 때 최대값 중 큰값을 반환한다.



## 느낀점
- dp문제를 많이 해결해 봐야겠다.  
- 알고리즘을 생각하는 것이 어려웠지만 구현은 어렵지 않았다.
- 그래도 구현은 해서 기분이 좋았다
