### ISSUE TITLE
[Level2] 순위 검색

### ISSUE THREAD

**Issue by junjange** [Uttug-Seuja/uttug-seuja-algorithm#399]
## 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/72412

## 풀이 사항
풀이 일자: 2023.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

## 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
## 문제 링크
#406 
## 풀이 사항
풀이 일자: 2023.09.08
풀이 시간: 4시간
채점 결과: 정답
예상 문제 유형: 이진탐색

## 풀이 방법
문제를 보고 주어진 query를 반복문을 통해서 모든 info를 매번 확인해서 카운트하려고 했었다.
하지만 단순 계산으로만 봐도 시간이 터질 거 같다는 생각이 들고 다른 방법을 생각해 봤지만 도저히 생각이 안 나서 카카오 문제 해설을 봤었다.
우선 주어진 query를 조건에 맞게 나눠주는 게 시간을 빠르게 단축할 수 있었다.
query를 나눠주면 info를 반복문을 통해서 주어진 조건에 해당하면 카운트하는 코드를 짜려고 했다. 하지만 이 부분에서도 모든 점수를 다 확인하면서 조건을 충족하는지 확인하는 순간 시간이 많이 걸렸다.
다른 사람들의 해설을 보면서 이진 탐색을 사용해서 빠르게 시간을 단축할 수 있다는 사실을 알았다.
이진 탐색을 찾아보면서 bisect_left을 알게 되었고 간단하게 구현할 수 있었다.

정답을 맞히기는 했지만 과연 이게 나의 코드인가?라는 질문에는 'NO'라는 대답이 나올 거 같다.
해설을 보고 풀어도 정확하게 이해하는 데 오랜 시간이 걸렸고 개선이 많이 필요해 보인다.

**Comment by junjange** [comment]
## 문제 링크
#401 

## 풀이 사항
풀이 일자: 2023.09.03
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 자료구조, 이진탐색

## 풀이 방법
- 문제를 보면 각 정보를 확인하고 해당 정보에 해당하는 인원을 찾아야한다.
- 그럼 점화식을 통해 문제를 해결하는 것과 그래프를 통해 해결하는 아닌 것으로 확인된다.
- 또한 문제의 요구 조건을 보게되면 시간 복잡도로 인해 완탐으로 문제를 못푸는 것을 확인할 수 있다.
- 그렇다면 이분 탐색이나 다른 알고리즘을 통해 푸는 것인데 여기까지 생각하고 더이상 생각하지 못했다.
- 이 다음부터는 풀이를 보고 문제를 수행했다.

**Comment by chanu2** [comment]
## 문제 링크
#407 

## 풀이 사항
풀이 일자: 2023.09.09
풀이 시간: 3시간
채점 결과: 오답
예상 문제 유형: 이진탐색

## 풀이 방법
- 문제를 처음 보고 info와 query를 하나하나 확인하려 했는데 시가복잡도를 넘을 것으로 생각했다.
- 고민을 여러번하고 해결하지 못할 것 같아서 풀이를 확인하였고 이진탐색을 사용해야 한다는 것을 알았다.
- 이진탐색에 대한 이해가 필요하다고 생각했고 푸는 방법을 보면서 구현에 집중했다.

**Comment by Leehunil** [comment]
## 문제 링크
#407 

## 풀이 사항
풀이 일자: 2023.09.09
풀이 시간: 3시간
채점 결과: 오답
예상 문제 유형: 이진탐색

## 풀이 방법
- 문제를 처음 보고 info와 query를 하나하나 확인하려 했는데 시가복잡도를 넘을 것으로 생각했다.
- 고민을 여러번하고 해결하지 못할 것 같아서 풀이를 확인하였고 이진탐색을 사용해야 한다는 것을 알았다.
- 이진탐색에 대한 이해가 필요하다고 생각했고 푸는 방법을 보면서 구현에 집중했다.
