### ISSUE TITLE
[Level3] 등굣길

### ISSUE THREAD

**Issue by GeonHui2** [Uttug-Seuja/uttug-seuja-algorithm#412]
## 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/42898

## 풀이 사항
풀이 일자: 2023.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

## 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by junjange** [comment]
## 문제 링크

## 풀이 사항
풀이 일자: 2023.09.16
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: DP, BFS

## 풀이 방법
- 문제를 보면 다음과 같다.
- 물에 잠기지 않은 지역을 통해 학교를 가야한다.
- 집에서 학교는 m x n 크기의 격자모양이다.
- 가장 왼쪽 위, 즉 집이 있는 곳의 좌표는 (1, 1)로 나타내고 가장 오른쪽 아래, 즉 학교가 있는 곳의 좌표는 (m, n)으로 나타다.
- 오른쪽과 아래쪽으로만 움직여 집에서 학교까지 갈 수 있는 최단경로를 찾아야한다.
- 최단경로의 개수를 1,000,000,007로 나눈 나머지를 리턴한다.
- 맨 마지막 조건에서 최단경로의 개수와 1,000,000,007로 나눈 나머지를 리턴한다는 것에서 DP라는 것을 인지할 수 있다.
- 그 위 조건들에서는 dfs, bfs를 통해 최단 경로를 탐색하면 된다는 것을 알 수 있다.
- 위 조건을 조합해서 문제를 풀면 된다.

**Comment by GeonHui2** [comment]
## 문제 링크
#413 
## 풀이 사항
풀이 일자: 2023.09.16
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: DP

## 풀이 방법
- 문제를 보고 유형이 DP라는 것을 알 수 있다.
- 반복문을 통해서 해당 dp에 도달하면 갈 수 있는 모든 경우의 수를 넣어주면 된다.
- 처음에는 물이 있는 곳을 나타내는 좌표를 피해서 계산하면 되는 줄 알았다.
- 하지만 물이 있는 곳을 나타내는 좌표가 내가 푸는 방식에서 [x, y]가 아니라 [y, x]로 주어졌다.
- 이 부분에서 시간이 조금 걸렸지만 DP를 풀어봤기에 어렵지 않게 풀었다.

**Comment by chanu2** [comment]
## 문제 링크
#414 
## 풀이 사항
풀이 일자: 2023.09.16
풀이 시간: 90분
채점 결과: 오답
예상 문제 유형: BFS

## 풀이 방법
- 문제를 잘 보지 못해 최단거리를 구해야하는 문제 인줄 알았다. 
- BFS를 통해서 하려했는데 잘못된 방법인거를 깨달았다
- 문제를 잘보고 풀어야 겠다.
- dp인걸 알았으니 다시 풀어봐야겠다

**Comment by Leehunil** [comment]
## 문제 링크
#415 

## 풀이 사항
풀이 일자: 2023.09.16
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: DP

## 풀이 방법
- 문제를 잘 읽어야 된다는 것을 깨달았다. 처음에는 최단거리 구하는 문제인줄 알고 BFS로 풀려고 했다.
- 계속해서 틀려서 답을 보니깐 DP로 푸는 문제인 것을 알았다.
- 어짜피 왼쪽이랑 위에서 오는게 최단거리이다.
- 그리고 맨위와 맨 왼쪽 줄은 최단 거리 경우의 수가 1이니깐 다 1로 둔다.
- 점화식은 왼쪽의 최단 거리의 수 + 위의 최단 거리의 수가 된다.
