### ISSUE TITLE
[Level2] 요격시스템

### ISSUE THREAD

**Issue by chanu2** [Uttug-Seuja/uttug-seuja-algorithm#422]
## 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/181188

## 풀이 사항
풀이 일자: 2023.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

## 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by junjange** [comment]
### 문제 링크

### 풀이 사항
풀이 일자: 2023.09.22
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 그리디, 정렬

### 풀이 방법
- 문제를 읽었을 때 반복문을 통해 순차적으로 어떠한 로직을 수행하면 될 것으로 판단했다.
- 개구간 (s, e)를 요격하는 것이므로 정렬을 통해 제일 가까운 개구간부터 요격을 해야한다.
- 정렬은 개구간의 길이가 짧은 것부터 요격을 해야 모든 구역을 확인하면서 요격할 수 있기 때문에 람다를 통해 e와 s를 오름차순으로 정렬했다.

**Comment by Leehunil** [comment]
### 문제 링크
#426

### 풀이 사항
풀이 일자: 2023.09.23
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 정렬

### 풀이 방법
- 처음에는 리스트에 배열을 저장해서 사이에 있는지 확인하고 마지막에 리스트 수를 반환함
- 하지만 시간 복잡도가 높고, 답도 틀렸어 다시 생각함
- 2차원 배열 첫번째 값으로 정렬을 함
- 그리고 비교 배열을 하나 두고 사이에 있는지 확인하고 사이에 있으면 비교 배열을 겹치는 부분으로 바꿈
- 사이에 없으면 count++하고 비교 배열을 현재 배열로 바꿈

**Comment by chanu2** [comment]
### 문제 링크
#427 

### 풀이 사항
풀이 일자: 2023.09.23
풀이 시간: 1시간 20분
채점 결과: 정답
예상 문제 유형: 그리디 

### 풀이 방법
- 문제를 읽고 정렬을 해야할것 같아서 첫번째 기준으로 정렬을 하고 그림을 그려보았다.
- 기준 구간을 생각해서 새로운 구간이 들어 왔을 때 겹치는 구간을 계속해서 동적으로 바꾼다. 
- 겹치는 부분이 없으면  result ++ 해주고 구간도 바꿔준다.

**Comment by GeonHui2** [comment]
### 문제 링크
#377 

### 풀이 사항
풀이 일자: 2023.08.20
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 정렬, 그리디

### 풀이 방법
- 문제를 읽고 정렬을 통해서 풀어야겠다는 생각을 했다.
- 현재 위치와 미사일의 시작점을 비교하면서 미사일의 시작점을 바꿨다.
- 각 미사일의 시작과 끝을 비교해서 최소한의 미사일의 갯수를 구했다.
