### ISSUE TITLE
[Level1] 공원 산책

### ISSUE THREAD

**Issue by junjange** [Uttug-Seuja/uttug-seuja-algorithm#429]
### 문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/172928

### 풀이 사항
풀이 일자: 2023.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 문제 링크
#431 

### 풀이 사항
풀이 일자: 2023.09.26
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 문제를 읽고 먼저 출발지의 좌표를 구했다.
- routes를 반복문을 통해서 각 route가 park 안에서 이동하는지 장애물을 지나가는지 확인했다.
- park 안에서 이동하고 장애물을 지나치지 않으면 해당하는 명령만큼 이동하고 조건에 부합하지 않으면 이전에 저장했던 좌표로 돌아간다.

**Comment by Leehunil** [comment]
### 문제 링크
#435 

### 풀이 사항
풀이 일자: 2023.09.26
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 장애물을 리스트로 따로 관리 하려고 했지만 시간 복잡도가 높다.
- EWSN을 map으로 따로 관리한다.
- 시작점을 구한다.
- 그리고 routes 하나씩 가져와서 해당 x값과 y값을 더한다.
- 더해서 배열을 넘어가거나 장애물을 만나면 break를 한다.
- 그리고 마지막 위치를 반환한다.

**Comment by junjange** [comment]
### 문제 링크
#435 

### 풀이 사항
풀이 일자: 2023.09.27
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 그냥 문제에서 요구하는 명령어대로 로봇을 옮기면 된다.
- 명령어를 수행할 수 없다면(범위를 벗어나거나 장애물로 가야하는 경우) 명령어를 수행하지 않는다.
- 명령어를 수행할 수 있다면 좌표를 바꾼다.

**Comment by chanu2** [comment]
### 문제 링크
#438 

### 풀이 사항
풀이 일자: 2023.09.27
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 그냥 문제에서 요구하는 대로 구현하면 될것 같았다.
- 명령어를 수행할 수 없다면(범위를 벗어나거나 장애물로 가야하는 경우) 명령어를 수행하지 않는다.
- 명령어를 수행할 수 있다면 좌표를 바꾼다.
